In [116]:
import pandas as pd
import numpy as np
import seaborn as sns

In [117]:
emails=pd.read_csv('C:\\Users\\HP\\Downloads\\archive (6)\\emails.csv')

In [118]:
emails

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [119]:
emails['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [120]:
emails.drop_duplicates(inplace=True)

In [121]:
emails

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [122]:
y=emails.spam.values

In [123]:
x=emails.text.values

In [124]:
from sklearn.model_selection import train_test_split

In [142]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [143]:
from sklearn.feature_extraction.text import CountVectorizer

In [144]:
cv=CountVectorizer()
x_train=cv.fit_transform(xtrain)

In [145]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [7, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4556, 33615))

In [146]:
x_test=cv.transform(xtest)

In [147]:
x_test.toarray()

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1139, 33615))

In [148]:
from sklearn.naive_bayes import MultinomialNB

In [149]:
model=MultinomialNB().fit(x_train,ytrain)

In [150]:
model.score(x_test,ytest)

0.9912203687445127

In [178]:
my_mails=['FULL SEND PODCAST: Gary Brecka EXPOSES the Pharmaceutical Industry and REVEALS RFK’s Plan!']

In [179]:
cv_my_mails=cv.transform(my_mails)

In [180]:
model.predict(cv_my_mails)

array([1])